name: login_1
description: A new Flutter project.

publish_to: 'none' # Remove this line if you want to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  cloud_firestore: ^6.2.0
  firebase_auth: ^6.3.0
  firebase_core: ^4.6.0
  firebase_database: ^12.2.0
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.4
  font_awesome_flutter: ^10.7.0
  provider: ^6.1.5+1
  table_calendar: ^3.2.0

  # Add other dependencies here

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter_native_splash:
  color: '#f7f6f1'
  color_dark: '#272727'
  image: assets/images/worker.png
  image_dark: assets/images/worker.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/workify_app_icon.png"
  adaptive_icon_background: "#FFA000"
  adaptive_icon_foreground: "assets/images/workify_app_icon.png"
  min_sdk_android: 21

flutter:
  assets:
    - assets/images/worker.png
    - assets/images/plumber.png
    - assets/images/workify_app_icon.png
