// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1I3DkusftDwv_9Wa1kOb69bVYimMxDU4',
    appId: '1:788288712446:android:28755f2d9c01af1420ffaf',
    messagingSenderId: '788288712446',
    projectId: 'workifyv2',
    databaseURL: 'https://workifyv2-default-rtdb.firebaseio.com',
    storageBucket: 'workifyv2.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGGea6ilGbWsnyvZS81NVCcKtmqVRmDmA',
    appId: '1:788288712446:web:20328ca2af3a041920ffaf',
    messagingSenderId: '788288712446',
    projectId: 'workifyv2',
    authDomain: 'workifyv2.firebaseapp.com',
    databaseURL: 'https://workifyv2-default-rtdb.firebaseio.com',
    storageBucket: 'workifyv2.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARdfd1x8Be_cGW4viYOdlQcQHyUodNS0E',
    appId: '1:788288712446:ios:0fe6673f1afcde4620ffaf',
    messagingSenderId: '788288712446',
    projectId: 'workifyv2',
    databaseURL: 'https://workifyv2-default-rtdb.firebaseio.com',
    storageBucket: 'workifyv2.firebasestorage.app',
    iosBundleId: 'com.example.login1',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARdfd1x8Be_cGW4viYOdlQcQHyUodNS0E',
    appId: '1:788288712446:ios:0fe6673f1afcde4620ffaf',
    messagingSenderId: '788288712446',
    projectId: 'workifyv2',
    databaseURL: 'https://workifyv2-default-rtdb.firebaseio.com',
    storageBucket: 'workifyv2.firebasestorage.app',
    iosBundleId: 'com.example.login1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGGea6ilGbWsnyvZS81NVCcKtmqVRmDmA',
    appId: '1:788288712446:web:df5f1010655b1ce420ffaf',
    messagingSenderId: '788288712446',
    projectId: 'workifyv2',
    authDomain: 'workifyv2.firebaseapp.com',
    databaseURL: 'https://workifyv2-default-rtdb.firebaseio.com',
    storageBucket: 'workifyv2.firebasestorage.app',
  );

}